Document: lagerdox
Title: Debian lagerdox Manual
Author: <insert document author here>
Abstract: This manual describes what lagerdox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lagerdox/lagerdox.sgml.gz

Format: postscript
Files: /usr/share/doc/lagerdox/lagerdox.ps.gz

Format: text
Files: /usr/share/doc/lagerdox/lagerdox.text.gz

Format: HTML
Index: /usr/share/doc/lagerdox/html/index.html
Files: /usr/share/doc/lagerdox/html/*.html
